# Generated by Django 3.0.7 on 2020-12-24 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201224_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'JobExperience'},
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(default=123, validators=[django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
